export const EventType = [
  { name: 'Casamento', index: 0 },
  { name: 'Feira', index: 1 },
  { name: 'Festa', index: 2 },
  { name: 'Festival', index: 3 },
  { name: 'Workshop', index: 4 },
  { name: 'Exibição', index: 5 },
  { name: 'Lançamento', index: 6 },
  { name: 'Campeonato', index: 7 },
  { name: 'Convenção', index: 8 },
  { name: 'Baile', index: 9 },
  { name: 'Seminário', index: 10 },
  { name: 'Assembléia', index: 11 },
  { name: 'Campanha', index: 12 },
  { name: 'Cerimônia', index: 13 },
  { name: 'Simpósio', index: 14 },
]
