sonar.projectKey=spring-myproject
sonar.projectName="QAZP"
sonar.projectVersion=1.0
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.token=sqa_2d3f5979278c4de18477cd381ecd7f5dfcd06908
sonar.jdbc.url=jdbc:postgresql://localhost:5432/sonarqube
sonar.jdbc.username=sonaruser
sonar.jdbc.password=sonarpassword