using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ZventsApi.Migrations
{
    /// <inheritdoc />
    public partial class MaterialSeed : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                 table: "Materials",
                 columns: ["Id", "Name", "Category", "Price", "CreatedDate", "IsDeleted"],
                 values: new object[,]
                 {
                     //Food
                    { Guid.NewGuid(), "Bolos de diversos sabores", 0, 50, DateTime.Now, false },
                    { Guid.NewGuid(), "Tortas doces", 0, 70, DateTime.Now, false },
                    { Guid.NewGuid(), "Tortas salgadas", 0, 80, DateTime.Now, false },
                    { Guid.NewGuid(), "Salgados sortidos (coxinha, empada, quibe, etc.)", 0, 30, DateTime.Now, false },
                    { Guid.NewGuid(), "Mini sanduíches", 0, 40, DateTime.Now, false },
                    { Guid.NewGuid(), "Cupcakes decorados", 0, 60, DateTime.Now, false },
                    { Guid.NewGuid(), "Brigadeiros gourmet", 0, 20, DateTime.Now, false },
                    { Guid.NewGuid(), "Beijinhos", 0, 20, DateTime.Now, false },
                    { Guid.NewGuid(), "Docinhos de festa variados", 0, 25, DateTime.Now, false },
                    { Guid.NewGuid(), "Bombons sortidos", 0, 30, DateTime.Now, false },
                    { Guid.NewGuid(), "Brownies", 0, 40, DateTime.Now, false },
                    { Guid.NewGuid(), "Biscoitos decorados", 0, 25, DateTime.Now, false },
                    { Guid.NewGuid(), "Bolachas recheadas", 0, 20, DateTime.Now, false },
                    { Guid.NewGuid(), "Cookies de diferentes sabores", 0, 25, DateTime.Now, false },
                    { Guid.NewGuid(), "Gelatinas coloridas", 0, 15, DateTime.Now, false },
                    { Guid.NewGuid(), "Mousses de frutas", 0, 35, DateTime.Now, false },
                    { Guid.NewGuid(), "Pavês de chocolate", 0, 45, DateTime.Now, false },
                    { Guid.NewGuid(), "Queijos diversos", 0, 40, DateTime.Now, false },
                    { Guid.NewGuid(), "Frios (presunto, peito de peru, salame, queijo prato, etc.)", 0, 40, DateTime.Now, false },
                    { Guid.NewGuid(), "Pães variados (francês, integral, de forma, etc.)", 0, 10, DateTime.Now, false },
                    { Guid.NewGuid(), "Patês e pastas (patê de atum, pasta de ricota, etc.)", 0, 25, DateTime.Now, false },
                    { Guid.NewGuid(), "Cuscuz paulista", 0, 30, DateTime.Now, false },
                    { Guid.NewGuid(), "Saladas de frutas", 0, 20, DateTime.Now, false },
                    { Guid.NewGuid(), "Doces em compota (figo, abóbora, etc.)", 0, 25, DateTime.Now, false },
                    { Guid.NewGuid(), "Geleias artesanais (morango, framboesa, etc.)", 0, 20, DateTime.Now, false },
                    { Guid.NewGuid(), "Bolinhos de bacalhau", 0, 50, DateTime.Now, false },
                    { Guid.NewGuid(), "Quiches", 0, 60, DateTime.Now, false },
                    { Guid.NewGuid(), "Empadões", 0, 70, DateTime.Now, false },
                    { Guid.NewGuid(), "Esfihas", 0, 30, DateTime.Now, false },
                    { Guid.NewGuid(), "Pizzas variadas", 0, 50, DateTime.Now, false },

                    //Decoration
                    { Guid.NewGuid(), "Arranjos de flores", 1, 80, DateTime.Now, false },
                    { Guid.NewGuid(), "Velas decorativas", 1, 30, DateTime.Now, false },
                    { Guid.NewGuid(), "Porta-retratos", 1, 15, DateTime.Now, false },
                    { Guid.NewGuid(), "Espelhos decorativos", 1, 100, DateTime.Now, false },
                    { Guid.NewGuid(), "Almofadas", 1, 20, DateTime.Now, false },
                    { Guid.NewGuid(), "Tapetes", 1, 150, DateTime.Now, false },
                    { Guid.NewGuid(), "Cortinas", 1, 80, DateTime.Now, false },
                    { Guid.NewGuid(), "Vasos decorativos", 1, 50, DateTime.Now, false },
                    { Guid.NewGuid(), "Estátuas e esculturas", 1, 200, DateTime.Now, false },
                    { Guid.NewGuid(), "Quadros decorativos", 1, 70, DateTime.Now, false },
                    { Guid.NewGuid(), "Molduras", 1, 10, DateTime.Now, false },
                    { Guid.NewGuid(), "Relógios de parede", 1, 40, DateTime.Now, false },
                    { Guid.NewGuid(), "Enfeites de mesa", 1, 25, DateTime.Now, false },
                    { Guid.NewGuid(), "Fitas decorativas", 1, 5, DateTime.Now, false },
                    { Guid.NewGuid(), "Lanternas", 1, 40, DateTime.Now, false },
                    { Guid.NewGuid(), "Banners decorativos", 1, 30, DateTime.Now, false },
                    { Guid.NewGuid(), "Placas de sinalização", 1, 20, DateTime.Now, false },
                    { Guid.NewGuid(), "Balões decorativos", 1, 15, DateTime.Now, false },
                    { Guid.NewGuid(), "Guirlandas", 1, 25, DateTime.Now, false },
                    { Guid.NewGuid(), "Cortinas de luzes", 1, 50, DateTime.Now, false },
                    { Guid.NewGuid(), "Letras luminosas", 1, 80, DateTime.Now, false },
                    { Guid.NewGuid(), "Adesivos de parede", 1, 10, DateTime.Now, false },
                    { Guid.NewGuid(), "Tecidos para decoração", 1, 30, DateTime.Now, false },
                    { Guid.NewGuid(), "Luminárias", 1, 60, DateTime.Now, false },
                    { Guid.NewGuid(), "Candelabros", 1, 100, DateTime.Now, false },
                    { Guid.NewGuid(), "Plantas decorativas", 1, 40, DateTime.Now, false },
                    { Guid.NewGuid(), "Móveis auxiliares", 1, 150, DateTime.Now, false },
                    { Guid.NewGuid(), "Cortinas de tecido", 1, 100, DateTime.Now, false },
                    { Guid.NewGuid(), "Cobertores", 1, 30, DateTime.Now, false },
                    { Guid.NewGuid(), "Cúpulas para luminárias", 1, 20, DateTime.Now, false },

                    //Utensils
                    { Guid.NewGuid(), "Rechaud", 2, 150, DateTime.Now, false },
                    { Guid.NewGuid(), "Bandeja para Servir", 2, 50, DateTime.Now, false },
                    { Guid.NewGuid(), "Cubas para Buffet", 2, 20, DateTime.Now, false },
                    { Guid.NewGuid(), "Travessa de Porcelana", 2, 30, DateTime.Now, false },
                    { Guid.NewGuid(), "Guardanapos de Pano", 2, 5, DateTime.Now, false },
                    { Guid.NewGuid(), "Porta Guardanapos", 2, 10, DateTime.Now, false },
                    { Guid.NewGuid(), "Pratos Descartáveis", 2, 2, DateTime.Now, false },
                    { Guid.NewGuid(), "Suporte para Guardanapos", 2, 15, DateTime.Now, false },
                    { Guid.NewGuid(), "Carrinho para Transporte de Alimentos", 2, 200, DateTime.Now, false },
                    { Guid.NewGuid(), "Cesto de Pães", 2, 30, DateTime.Now, false },
                    { Guid.NewGuid(), "Panelas de Alumínio", 2, 50, DateTime.Now, false },
                    { Guid.NewGuid(), "Frigideiras Antiaderentes", 2, 40, DateTime.Now, false },
                    { Guid.NewGuid(), "Espátulas de Silicone", 2, 8, DateTime.Now, false },
                    { Guid.NewGuid(), "Conjunto de Facas", 2, 80, DateTime.Now, false },
                    { Guid.NewGuid(), "Tábua de Corte", 2, 15, DateTime.Now, false },
                    { Guid.NewGuid(), "Formas para Bolos", 2, 10, DateTime.Now, false },
                    { Guid.NewGuid(), "Ralador de Queijo", 2, 7, DateTime.Now, false },
                    { Guid.NewGuid(), "Abridor de Latas", 2, 5, DateTime.Now, false },
                    { Guid.NewGuid(), "Espremedor de Frutas", 2, 20, DateTime.Now, false },
                    { Guid.NewGuid(), "Peneira de Cozinha", 2, 10, DateTime.Now, false },
                    { Guid.NewGuid(), "Descascador de Frutas", 2, 3, DateTime.Now, false },
                    { Guid.NewGuid(), "Coador de Café", 2, 5, DateTime.Now, false },
                    { Guid.NewGuid(), "Pegador de Massas", 2, 4, DateTime.Now, false },
                    { Guid.NewGuid(), "Rolo de Massa", 2, 10, DateTime.Now, false },
                    { Guid.NewGuid(), "Conjunto de Medidores", 2, 8, DateTime.Now, false },
                    { Guid.NewGuid(), "Escumadeira", 2, 6, DateTime.Now, false },
                    { Guid.NewGuid(), "Espremedor de Alho", 2, 4, DateTime.Now, false },
                    { Guid.NewGuid(), "Descaroçador de Azeitonas", 2, 5, DateTime.Now, false },
                    { Guid.NewGuid(), "Balança de Cozinha", 2, 15, DateTime.Now, false },
                    { Guid.NewGuid(), "Jarra Medidora", 2, 7, DateTime.Now, false },
                    { Guid.NewGuid(), "Canetas Esferográficas", 2, 2, DateTime.Now, false },
                    { Guid.NewGuid(), "Bloco de Notas", 2, 3, DateTime.Now, false },
                    { Guid.NewGuid(), "Clips Metálicos", 2, 1, DateTime.Now, false },
                    { Guid.NewGuid(), "Grampeador de Mesa", 2, 5, DateTime.Now, false },
                    { Guid.NewGuid(), "Caixa de Arquivo Morto", 2, 10, DateTime.Now, false },
                    { Guid.NewGuid(), "Suporte para Canetas", 2, 3, DateTime.Now, false },
                    { Guid.NewGuid(), "Agenda de Compromissos", 2, 5, DateTime.Now, false },
                    { Guid.NewGuid(), "Calculadora Básica", 2, 15, DateTime.Now, false },
                    { Guid.NewGuid(), "Fichário A4", 2, 8, DateTime.Now, false },
                    { Guid.NewGuid(), "Tesoura de Uso Geral", 2, 7, DateTime.Now, false },
                    { Guid.NewGuid(), "Grampeador de Parede", 2, 10, DateTime.Now, false },
                    { Guid.NewGuid(), "Apontador de Lápis", 2, 2, DateTime.Now, false },
                    { Guid.NewGuid(), "Organizador de Mesa", 2, 8, DateTime.Now, false },
                    { Guid.NewGuid(), "Alicate de Grampos", 2, 12, DateTime.Now, false },
                    { Guid.NewGuid(), "Caixa de Clipes", 2, 3, DateTime.Now, false },
                    { Guid.NewGuid(), "Bloco de Rascunho", 2, 4, DateTime.Now, false },
                    { Guid.NewGuid(), "Perfurador de Papel", 2, 10, DateTime.Now, false },
                    { Guid.NewGuid(), "Tesoura de Ponta Fina", 2, 5, DateTime.Now, false },
                    { Guid.NewGuid(), "Organizador de Cabos", 2, 7, DateTime.Now, false },
                    { Guid.NewGuid(), "Protetor de Tomadas", 2, 3, DateTime.Now, false },

                    //Furniture
                    { Guid.NewGuid(), "Mesas", 4, 300, DateTime.Now, false },
                    { Guid.NewGuid(), "Cadeiras", 4, 100, DateTime.Now, false },
                    { Guid.NewGuid(), "Sofás", 4, 800, DateTime.Now, false },
                    { Guid.NewGuid(), "Poltronas", 4, 500, DateTime.Now, false },
                    { Guid.NewGuid(), "Estantes", 4, 200, DateTime.Now, false },
                    { Guid.NewGuid(), "Armários", 4, 600, DateTime.Now, false },
                    { Guid.NewGuid(), "Prateleiras", 4, 150, DateTime.Now, false },
                    { Guid.NewGuid(), "Cômodas", 4, 400, DateTime.Now, false },
                    { Guid.NewGuid(), "Camas", 4, 1000, DateTime.Now, false },
                    { Guid.NewGuid(), "Mesa de centro", 4, 250, DateTime.Now, false },
                    { Guid.NewGuid(), "Racks", 4, 350, DateTime.Now, false },
                    { Guid.NewGuid(), "Mesa de jantar", 4, 600, DateTime.Now, false },
                    { Guid.NewGuid(), "Bancadas de trabalho", 4, 400, DateTime.Now, false },
                    { Guid.NewGuid(), "Aparadores", 4, 300, DateTime.Now, false },
                    { Guid.NewGuid(), "Biombos", 4, 150, DateTime.Now, false },
                    { Guid.NewGuid(), "Bancos", 4, 80, DateTime.Now, false },
                    { Guid.NewGuid(), "Cadeiras de escritório", 4, 120, DateTime.Now, false },
                    { Guid.NewGuid(), "Mesa lateral", 4, 150, DateTime.Now, false },
                    { Guid.NewGuid(), "Puffs", 4, 70, DateTime.Now, false },
                    { Guid.NewGuid(), "Bancadas de bar", 4, 200, DateTime.Now, false },
                    { Guid.NewGuid(), "Bancos altos", 4, 100, DateTime.Now, false },
                    { Guid.NewGuid(), "Balcões", 4, 300, DateTime.Now, false },
                    { Guid.NewGuid(), "Mesa de estudo", 4, 180, DateTime.Now, false },
                    { Guid.NewGuid(), "Bancadas de cozinha", 4, 250, DateTime.Now, false },
                    { Guid.NewGuid(), "Mesa de centro elevável", 4, 350, DateTime.Now, false },
                    { Guid.NewGuid(), "Escrivaninhas", 4, 200, DateTime.Now, false },
                    { Guid.NewGuid(), "Mesa de cabeceira", 4, 100, DateTime.Now, false },
                    { Guid.NewGuid(), "Mesa de canto", 4, 120, DateTime.Now, false },
                    { Guid.NewGuid(), "Mesa de bar", 4, 150, DateTime.Now, false },
                    { Guid.NewGuid(), "Bancadas de estudo", 4, 200, DateTime.Now, false },

                    //HumanResources
                    { Guid.NewGuid(), "Apresentador", 5, 300, DateTime.Now, false },
                    { Guid.NewGuid(), "Segurança", 5, 500, DateTime.Now, false },
                    { Guid.NewGuid(), "Cozinheiro", 5, 400, DateTime.Now, false },
                    { Guid.NewGuid(), "Recepcionista", 5, 350, DateTime.Now, false },
                    { Guid.NewGuid(), "Motorista", 5, 250, DateTime.Now, false },
                    { Guid.NewGuid(), "Auxiliar de Limpeza", 5, 180, DateTime.Now, false },
                    { Guid.NewGuid(), "Assistente Administrativo", 5, 350, DateTime.Now, false },
                    { Guid.NewGuid(), "Técnico de Informática", 5, 400, DateTime.Now, false },
                    { Guid.NewGuid(), "Assistente de Recursos Humanos", 5, 400, DateTime.Now, false },
                    { Guid.NewGuid(), "Analista de Marketing", 5, 500, DateTime.Now, false },
                    { Guid.NewGuid(), "Assistente Financeiro", 5, 350, DateTime.Now, false },
                    { Guid.NewGuid(), "Entregador", 5, 200, DateTime.Now, false },
                    { Guid.NewGuid(), "Garçom", 5, 250, DateTime.Now, false },
                    { Guid.NewGuid(), "Bartender", 5, 300, DateTime.Now, false },
                    { Guid.NewGuid(), "Chefe de Cozinha", 5, 600, DateTime.Now, false },
                    { Guid.NewGuid(), "Promotor de Eventos", 5, 400, DateTime.Now, false },
                    { Guid.NewGuid(), "Fotógrafo", 5, 350, DateTime.Now, false },
                    { Guid.NewGuid(), "Segurança Eletrônica", 5, 500, DateTime.Now, false },
                    { Guid.NewGuid(), "Auxiliar de Produção", 5, 250, DateTime.Now, false },
                    { Guid.NewGuid(), "Atendente de Bar", 5, 180, DateTime.Now, false },
                    { Guid.NewGuid(), "Maquiador", 5, 300, DateTime.Now, false },
                    { Guid.NewGuid(), "Bombeiro", 5, 500, DateTime.Now, false },
                    { Guid.NewGuid(), "Recepcionista de Eventos", 5, 350, DateTime.Now, false },
                    { Guid.NewGuid(), "Copeiro", 5, 200, DateTime.Now, false },
                    { Guid.NewGuid(), "Cozinheiro Industrial", 5, 400, DateTime.Now, false },
                    { Guid.NewGuid(), "Assistente de Produção", 5, 350, DateTime.Now, false },
                    { Guid.NewGuid(), "Designer Gráfico", 5, 450, DateTime.Now, false },
                    { Guid.NewGuid(), "Auxiliar de Almoxarifado", 5, 250, DateTime.Now, false },
                    { Guid.NewGuid(), "Segurança Patrimonial", 5, 500, DateTime.Now, false },
                    { Guid.NewGuid(), "Auxiliar de Eventos", 5, 180, DateTime.Now, false },
                    { Guid.NewGuid(), "Supervisor de Eventos", 5, 600, DateTime.Now, false },

                     //RealEstate
                    { Guid.NewGuid(), "Salão de Festas", 6, 5000, DateTime.Now, false },
                    { Guid.NewGuid(), "Casa de Eventos", 6, 7000, DateTime.Now, false },
                    { Guid.NewGuid(), "Espaço para Eventos", 6, 6000, DateTime.Now, false },
                    { Guid.NewGuid(), "Sítio para Festas", 6, 8000, DateTime.Now, false },
                    { Guid.NewGuid(), "Chácara para Eventos", 6, 9000, DateTime.Now, false },
                    { Guid.NewGuid(), "Casa de Campo para Festas", 6, 7500, DateTime.Now, false },
                    { Guid.NewGuid(), "Fazenda para Eventos", 6, 10000, DateTime.Now, false },
                    { Guid.NewGuid(), "Mansão para Festas", 6, 12000, DateTime.Now, false },
                    { Guid.NewGuid(), "Casarão para Eventos", 6, 10000, DateTime.Now, false },
                    { Guid.NewGuid(), "Galpão de Eventos", 6, 5000, DateTime.Now, false },
                    { Guid.NewGuid(), "Espaço Gourmet", 6, 4000, DateTime.Now, false },
                    { Guid.NewGuid(), "Lounge para Eventos", 6, 3000, DateTime.Now, false },
                    { Guid.NewGuid(), "Terraço para Eventos", 6, 3500, DateTime.Now, false },
                    { Guid.NewGuid(), "Casa de Praia para Festas", 6, 9000, DateTime.Now, false },
                    { Guid.NewGuid(), "Casa de Sítio para Eventos", 6, 8500, DateTime.Now, false },
                    { Guid.NewGuid(), "Casa de Campo para Casamentos", 6, 10000, DateTime.Now, false },
                    { Guid.NewGuid(), "Casa de Praia para Casamentos", 6, 11000, DateTime.Now, false },
                    { Guid.NewGuid(), "Espaço para Cerimônias", 6, 8000, DateTime.Now, false },
                    { Guid.NewGuid(), "Quintal para Eventos", 6, 2000, DateTime.Now, false },
                    { Guid.NewGuid(), "Salão de Festas com Piscina", 6, 6000, DateTime.Now, false },
                    { Guid.NewGuid(), "Chácara com Área de Churrasco", 6, 7000, DateTime.Now, false },
                    { Guid.NewGuid(), "Casa de Campo com Piscina", 6, 9000, DateTime.Now, false },
                    { Guid.NewGuid(), "Espaço com Jardim para Eventos", 6, 5500, DateTime.Now, false },
                    { Guid.NewGuid(), "Casa de Fazenda para Festas", 6, 11000, DateTime.Now, false },
                    { Guid.NewGuid(), "Mansão com Vista Panorâmica", 6, 15000, DateTime.Now, false },
                    { Guid.NewGuid(), "Casa Colonial para Eventos", 6, 8000, DateTime.Now, false },
                    { Guid.NewGuid(), "Casa Moderna para Festas", 6, 10000, DateTime.Now, false },
                    { Guid.NewGuid(), "Loft para Eventos", 6, 4500, DateTime.Now, false },
                    { Guid.NewGuid(), "Castelo para Festas", 6, 20000, DateTime.Now, false },

                    //Entertainment
                    { Guid.NewGuid(), "Iluminação de palco", 7, 800, DateTime.Now, false },
                    { Guid.NewGuid(), "Equipamento de som", 7, 1500, DateTime.Now, false },
                    { Guid.NewGuid(), "Equipamento de vídeo", 7, 2000, DateTime.Now, false },
                    { Guid.NewGuid(), "Microfones", 7, 200, DateTime.Now, false },
                    { Guid.NewGuid(), "Caixas de som", 7, 500, DateTime.Now, false },
                    { Guid.NewGuid(), "Telões", 7, 1200, DateTime.Now, false },
                    { Guid.NewGuid(), "Projetores", 7, 1000, DateTime.Now, false },
                    { Guid.NewGuid(), "Painéis de LED", 7, 3000, DateTime.Now, false },
                    { Guid.NewGuid(), "Máquinas de fumaça", 7, 300, DateTime.Now, false },
                    { Guid.NewGuid(), "Equipamentos de karaokê", 7, 400, DateTime.Now, false },
                    { Guid.NewGuid(), "Equipamentos de DJ", 7, 1500, DateTime.Now, false },
                    { Guid.NewGuid(), "Tendas para eventos", 7, 1500, DateTime.Now, false },
                    { Guid.NewGuid(), "Pisos para eventos", 7, 1000, DateTime.Now, false },
                    { Guid.NewGuid(), "Barras de LED", 7, 500, DateTime.Now, false },
                    { Guid.NewGuid(), "Plataformas para shows", 7, 2000, DateTime.Now, false },
                    { Guid.NewGuid(), "Palcos móveis", 7, 3000, DateTime.Now, false },
                    { Guid.NewGuid(), "Atrações artísticas", 7, 5000, DateTime.Now, false },
                    { Guid.NewGuid(), "Máquinas de neve", 7, 500, DateTime.Now, false },
                    { Guid.NewGuid(), "Máquinas de bolhas", 7, 300, DateTime.Now, false },
                    { Guid.NewGuid(), "Máquinas de confete", 7, 400, DateTime.Now, false },
                    { Guid.NewGuid(), "Máquinas de CO2", 7, 800, DateTime.Now, false },
                    { Guid.NewGuid(), "Geradores de efeitos especiais", 7, 2000, DateTime.Now, false },
                    { Guid.NewGuid(), "Máquinas de luz negra", 7, 400, DateTime.Now, false },
                    { Guid.NewGuid(), "Carpetes vermelhos", 7, 200, DateTime.Now, false },
                    { Guid.NewGuid(), "Placas de sinalização de eventos", 7, 50, DateTime.Now, false },
                    { Guid.NewGuid(), "Pulseiras de identificação", 7, 100, DateTime.Now, false },
                    { Guid.NewGuid(), "Tendas de brinquedos", 7, 1000, DateTime.Now, false },
                    { Guid.NewGuid(), "Balões de hélio", 7, 150, DateTime.Now, false },
                    { Guid.NewGuid(), "Pulseiras de LED", 7, 300, DateTime.Now, false },
                    { Guid.NewGuid(), "Pinturas faciais", 7, 200, DateTime.Now, false },

                    //Marketing
                    { Guid.NewGuid(), "Banners promocionais", 8, 100, DateTime.Now, false },
                    { Guid.NewGuid(), "Cartazes", 8, 50, DateTime.Now, false },
                    { Guid.NewGuid(), "Panfletos", 8, 20, DateTime.Now, false },
                    { Guid.NewGuid(), "Folders", 8, 30, DateTime.Now, false },
                    { Guid.NewGuid(), "Brindes promocionais", 8, 200, DateTime.Now, false },
                    { Guid.NewGuid(), "Camisetas promocionais", 8, 150, DateTime.Now, false },
                    { Guid.NewGuid(), "Canetas personalizadas", 8, 5, DateTime.Now, false },
                    { Guid.NewGuid(), "Crachás personalizados", 8, 8, DateTime.Now, false },
                    { Guid.NewGuid(), "Adesivos promocionais", 8, 10, DateTime.Now, false },
                    { Guid.NewGuid(), "Banner eletrônico", 8, 1000, DateTime.Now, false },
                    { Guid.NewGuid(), "Carros de som", 8, 500, DateTime.Now, false },
                    { Guid.NewGuid(), "Materiais impressos", 8, 100, DateTime.Now, false },
                    { Guid.NewGuid(), "Anúncios em jornais", 8, 200, DateTime.Now, false },
                    { Guid.NewGuid(), "Anúncios em revistas", 8, 300, DateTime.Now, false },
                    { Guid.NewGuid(), "Anúncios em rádio", 8, 400, DateTime.Now, false },
                    { Guid.NewGuid(), "Anúncios em televisão", 8, 1000, DateTime.Now, false },
                    { Guid.NewGuid(), "Anúncios online", 8, 500, DateTime.Now, false },
                 });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
